### ISSUE TITLE
nodejs el7 Repo Metadata Not Found

### ISSUE THREAD

**Issue by bgeels** [nodesource/distributions#1105] opened 2020-09-10 16:43 UTC
Having issues installing the nodejs package. Looks like the repo metadata is missing.

https://rpm.nodesource.com/pub_12.x/el/7/SRPMS/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

**Comment by JesusPaz** [comment] 2022-03-08 15:25
Duplicate of #998

**Closed by JesusPaz** 2022-03-08 15:25 UTC
Labels: bug, duplicate
