### ISSUE TITLE
[ERROR] Node.js 18 on contos 9 Installation fail SHA1

### ISSUE THREAD

**Issue by phoneben** [nodesource/distributions#1693] opened 2023-10-20 05:03 UTC
warning: Signature not supported. Hash algorithm SHA1 not available.
Key import failed (code 2). Failing package is: nodejs-2:18.18.2-1nodesource.x86_64

**Distribution Information:**
 - OS: centos
 - Version 9

**Node Version:**
Node.js v18.18.2:

**To Reproduce**
sudo yum install nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1

**Expected behavior**
just work 

**Additional context**
the work around for now is to allow sha 1
update-crypto-policies --set DEFAULT:SHA1 
reboot
after change it back 
update-crypto-policies --set DEFAULT
reboot
as in post from redhat 
https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9
sha1 is depreciated by default

**Comment by nexryai** [comment] 2023-11-08 13:40
I have the same problem on RockyLinux 9 and can't install Node20.  
I don't want to allow sha1 because it's not good for security.

**Comment by divishav** [comment] 2023-11-09 09:41
Facing the same error in Oracle linux 9, failing to install Node 18.18.2

**Comment by jcox10** [comment] 2023-12-18 23:32
Duplicate of https://github.com/nodesource/distributions/issues/1653

**Comment by JesusPaz** [comment] 2024-01-02 22:44
This issue is now resolved, please run the new scripts:
```
curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
yum install -y nodejs
```

**Closed by JesusPaz** 2024-01-02 22:44 UTC
Labels: bug, waiting on response from NodeSource

**Comment by BioEngLuisPereira** [comment] 2024-01-31 23:07
Well...did so and nothing changed:

```
The GPG keys listed for the "Node.js Packages for Linux RPM based distros - x86_64" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.. Failing package is: nodejs-2:18.19.0-1nodesource.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/NODESOURCE-NSOLID-GPG-SIGNING-KEY-EL
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
```


Did it worked for everyone else?
I'm on Oracle linux 9.

Thank you.

**Comment by JesusPaz** [comment] 2024-01-31 23:28
@BioEngLuisPereira doesn't work for you?
I don't have this problem, try running the script.
```
curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
dnf install -y nodejs
```
![image](https://github.com/nodesource/distributions/assets/27715376/f8c8b905-ec23-48d1-9998-c5f24c7023e7)

**Comment by BioEngLuisPereira** [comment] 2024-02-01 11:27
Thanks for the quick repply.
Unfortunaly I'm not being able to test it since I'm at the free instances limits =\. 
After this issue, I went straight to Oracle Linux 8 instance and all worked well, had to install nodejs v18 though.
So, your suggestion could solve the issue since it points to v18 instead of v20.
It might come to be usefull to the next guy.

Thank you.

**Comment by jcox10** [comment] 2024-02-01 15:35
I don't think your gpgkey is correct in the repo file, it should be `NODESOURCE-GPG-SIGNING-KEY-EL`. Installing as @JesusPaz has recommended should fix it.
