### ISSUE TITLE
Error:- You don't appear to be running an Enterprise Linux based system

### ISSUE THREAD

**Issue by imsuraj22** [nodesource/distributions#1419] opened 2022-07-14 12:43 UTC
You don't appear to be running an Enterprise Linux based system,
please contact NodeSource at https://github.com/nodesource/distributions/issues
if you think this is incorrect or would like your distribution to be considered
for support.

**Comment by JesusPaz** [comment] 2022-09-12 21:19
Duplicate of #888

**Closed by JesusPaz** 2022-09-12 21:19 UTC
Labels: help wanted
