### ISSUE TITLE
Keep older nodejs 5.x versions available?

### ISSUE THREAD

**Issue by msabramo** [nodesource/distributions#192] opened 2015-12-09 18:34 UTC
A few days ago we were pinning to `nodejs=5.0.*` and our playbooks for spinning up VMs were working. Then NodeJS 5.1.1 was released on 2015-12-04 (5 days ago!) and our stuff broke -- it seems that when 5.1.1 was released all of the 5.0.* versions became unavailable?

So just yesterday someone changed it from `nodejs=5.0.*` to `nodejs=5.1.*` and everything was working again.

Today it's broken again. I'm presuming this is because NodeJS 5.2 was released today (2015-12-09) and the all of the `5.1.*` versions became unavailable?

What is the process for pinning to some known stable version of NodeJS? I could change it to `5.*` but that seems risky to grab whatever the latest 5.x version of NodeJS is, as we have not tested our apps with these newer versions. I think I'd feel more comfortable pinning to a 5.1.2 or at least 5.1.*, but perhaps this is not possible?

What is the recommended way to get a stable version of NodeJS that won't keep going away as we'd prefer for all of our VMs spun up over time to have the same version?

Are the NodeSource repos intended only for development and not for production use? Should we use the Ubuntu repos instead of the NodeSource ones to get the stability we want?

**Comment by wblankenship** [comment] 2015-12-09 19:44
Hey @msabramo. @chrislea may have a better solution than I for pinning to a version, but these repositories are certainly maintained with production use in mind.

The `.deb` files are still on the server: https://deb.nodesource.com/node_5.x/pool/main/n/nodejs/

For my Docker images I am pinning to specific versions by using `dpkg -i`. An example can be found here: https://github.com/nodesource/docker-node/tree/master/debian/jessie/node/5.1.1

Unsure what the proper steps are to get the same behaviour out of `apt`. Perhaps @rvagg or @chrislea can chime in?

**Comment by msabramo** [comment] 2015-12-09 19:47
Ah you're right, the .deb files are still there. I wonder if they are just not being included in the apt index files...?

**Comment by wblankenship** [comment] 2015-12-10 15:38
This is a duplicate of https://github.com/nodesource/distributions/issues/33

**Closed by wblankenship** 2015-12-10 15:38 UTC
