### ISSUE TITLE
[ERROR] SSL Certificate for https://deb.nodesource.com exired.

### ISSUE THREAD

**Issue by DeWaRs1206** [nodesource/distributions#1510] opened 2023-01-31 17:53 UTC
**Describe your bug**

![Screenshot 2023-01-31 at 18 48 35](https://user-images.githubusercontent.com/11579317/215842856-d045ff0d-1c39-4c76-9b97-a0256d76c16b.png)

**Distribution Information:**
Any Browser.

**Node Version:**
 - Node: Any version.

**To Reproduce**
1. Go to https://deb.nodesource.com/node_14.x/ 
2. SSL Error is raised by the browser.

**Expected behavior**
No SSL error.

**Comment by MarianoRD** [comment] 2023-01-31 17:54
Can confirm this, this is a really huge bug 😮

**Comment by mvl22** [comment] 2023-01-31 17:54
Duplicate of #1507.

**Comment by JesusPaz** [comment] 2023-01-31 19:06
Duplicate of #1507

**Closed by JesusPaz** 2023-01-31 19:06 UTC
Labels: bug
