### ISSUE TITLE
Your distribution, identified as "fedora-release-28-1.noarch", is not currently supported (Node 10.x)

### ISSUE THREAD

**Issue by foo-dogsquared** [nodesource/distributions#659] opened 2018-05-06 22:29 UTC
Hello!
Tried to install Node 10.x through this command: 
curl --silent --location https://rpm.nodesource.com/setup_10.x | sudo bash -

And it gave the titled error.

Well, Fedora 28 does have the Node 8.x, thankfully. I just want to report about that (and I still want to test out Node 10.x so...). Any help is appreciated!

**Comment by chrislea** [comment] 2018-05-06 22:31
Duplicate of https://github.com/nodesource/distributions/issues/655, closing.

**Closed by chrislea** 2018-05-06 22:31 UTC
