### ISSUE TITLE
bunsen-hydrogen is not currently supported

### ISSUE THREAD

**Issue by perchslayer** [nodesource/distributions#248] opened 2016-03-13 00:43 UTC
Unable to install this very important package (either 4.x or 5.x) on [Bunsen Labs](https://www.bunsenlabs.org/) (based on Debian Jessie). Could you please consider making this available for Bunsen Labs, as it is the sort of package (like Arch Linux or Gentoo) that warrants such. 

Thank you.

**Comment by rvagg** [comment] 2016-03-14 02:49
dupe of https://github.com/nodesource/distributions/issues/241

**Closed by rvagg** 2016-03-14 02:49 UTC
