### ISSUE TITLE
cannot install by specific version

### ISSUE THREAD

**Issue by bisrael** [nodesource/distributions#380] opened 2016-11-04 21:00 UTC
Ubuntu 16.04 inside Docker image:

```

RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -

RUN apt-get -yy update && apt-get -yy install \
  nginx \
  nodejs=6.9.1 \
  && rm -rf /var/lib/apt/lists/*
```

Fails with:

```
E: Version '6.9.1' for 'nodejs' was not found
```

Removing the version succeeds.

Being able to peg to a specific version is crucial for reproducible environments

Thanks!

**Comment by chrislea** [comment] 2016-11-05 00:48
Dupe of #307 , please refer there for explanation.

**Closed by chrislea** 2016-11-05 00:48 UTC
