### ISSUE TITLE
Debian GNU/Linux 7.9 (wheezy) not currently supported

### ISSUE THREAD

**Issue by extensionsapp** [nodesource/distributions#232] opened 2016-02-15 16:53 UTC
debian-7-amd64-minimal
OpenVZ

```
## Installing packages required for setup: apt-transport-https...

+ apt-get install -y apt-transport-https > /dev/null 2>&1

## Confirming "wheezy" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_5.x/dists/wheezy/Release'

## Your distribution, identified as "wheezy", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.9 (wheezy)
Release:        7.9
Codename:       wheezy

```

**Comment by extensionsapp** [comment] 2016-02-16 00:47
Fix:

```
~# apt-get install ca-certificates
```

**Comment by BartManX** [comment] 2016-04-17 19:09
im having this same problem .. 
the fix didnt help .... 
`root@server:~# apt-get install ca-certificates
Reading package lists... Done
Building dependency tree
Reading state information... Done
ca-certificates is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
`

**Comment by chrislea** [comment] 2016-04-18 19:22
Dupe of #46

**Closed by chrislea** 2016-04-18 19:22 UTC
