### ISSUE TITLE
Request on Issue (Your distribution, identified as "vanessa", is not currently supported)

### ISSUE THREAD

**Issue by If-Ad** [nodesource/distributions#1428] opened 2022-08-08 19:04 UTC
I'm having issues on installing nodejs version : 18.7.0 on my linux machine running Linux Mint 21 (Vanessa).
After running the command from the given instructions https://github.com/nodesource/distributions/blob/master/README.md#debinstall
It shows an error like this :

 Your distribution, identified as "vanessa", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by kanasimi** [comment] 2022-08-08 22:48
Duplicate of #1424

**Comment by AndriyMeleshko** [comment] 2022-08-10 07:27
## Confirming "vanessa" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_16.x/dists/vanessa/Release'

## Your distribution, identified as "vanessa", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by Comprise** [comment] 2022-08-10 13:10
> I'm having issues on installing nodejs version : 18.7.0 on my linux machine running Linux Mint 21 (Vanessa). After running the command from the given instructions https://github.com/nodesource/distributions/blob/master/README.md#debinstall It shows an error like this :
> 
> Your distribution, identified as "vanessa", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

`curl -fsSL https://raw.githubusercontent.com/nodesource/distributions/master/deb/setup_lts.x | sudo -E bash -`

**Comment by kanasimi** [comment] 2022-08-10 20:46
I also find error:
```
# curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
```
get
```
## Confirming "vanessa" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_18.x/dists/vanessa/Release'

## Your distribution, identified as "vanessa", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by ailtonbsj** [comment] 2022-08-17 04:22
Run sequentially on terminal:

```bash
KEYRING=/usr/share/keyrings/nodesource.gpg

curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | sudo tee "$KEYRING" >/dev/null

echo "deb [signed-by=$KEYRING] https://deb.nodesource.com/node_18.x jammy main" | sudo tee /etc/apt/sources.list.d/nodesource.list

sudo apt-get update

sudo apt-get install nodejs
```

**Comment by JesusPaz** [comment] 2022-08-17 11:38
Changes to support Linux Mint are already in our repo. They will be updated in our CDN soon.

**Closed by JesusPaz** 2022-08-17 11:38 UTC

**Comment by KaKi87** [comment] 2022-08-17 11:42
> Changes to support Linux Mint [...] will be updated in our CDN soon.

Thanks for replying to [my question](https://github.com/nodesource/distributions/pull/1422#issuecomment-1209655864) from more than a week ago.
