### ISSUE TITLE
Can't install nodejs 10.x, failed at 98% of the download

### ISSUE THREAD

**Issue by hbouhadji** [nodesource/distributions#1091] opened 2020-07-23 22:06 UTC
Hello, it's impossible to install node 10.x

Steps to reproduce with docker:
```
docker run -it amazonlinux sh
```
then
```
yum install -y gcc-c++ make
curl -sL https://rpm.nodesource.com/setup_10.x | bash -E
yum remove -y nodejs npm && yum install -y nodejs
```

Result:
```
sh-4.2# yum remove -y nodejs npm && yum install -y nodejs
Loaded plugins: ovl, priorities
No Match for argument: nodejs
No Match for argument: npm
No Packages marked for removal
Loaded plugins: ovl, priorities
nodesource                                                                                                                                                                   | 2.5 kB  00:00:00     
nodesource/x86_64/primary_db                                                                                                                                                 |  46 kB  00:00:00     
Resolving Dependencies
--> Running transaction check
---> Package nodejs.x86_64 2:10.22.0-1nodesource will be installed
--> Finished Dependency Resolution

Dependencies Resolved

====================================================================================================================================================================================================
 Package                                   Arch                                      Version                                                    Repository                                     Size
====================================================================================================================================================================================================
Installing:
 nodejs                                    x86_64                                    2:10.22.0-1nodesource                                      nodesource                                     20 M

Transaction Summary
====================================================================================================================================================================================================
Install  1 Package

Total download size: 20 M
Installed size: 61 M
Downloading packages:
nodejs-10.22.0-1nodesource.x86 FAILED                                               98% [=======================================================================- ] 3.0 MB/s |  20 MB  00:00:00 ETA 
https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodejs-10.22.0-1nodesource.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=nodesource clean metadata
Trying other mirror.


Error downloading packages:
  2:nodejs-10.22.0-1nodesource.x86_64: [Errno 256] No more mirrors to try.
```

My website was down for 3hours because of this :'(

**Comment by mattcharlton** [comment] 2020-07-24 10:11
Experiencing the same issue - preventing deployments from AWS in several environments due to the repo being broken.

**Comment by hbouhadji** [comment] 2020-07-24 10:16
@mattcharlton you can replace to setup_12.x to install nodejs 12 instead (not broken) but you have to be sure all your dependencies works with node 12

**Comment by mattcharlton** [comment] 2020-07-24 10:21
We're not in a position to do that sadly because of our development lifecycle and because of multiple dependencies.  It was a struggle to get the developers to upgrade from nodejs 8 ;)

**Comment by efeubiqube** [comment] 2020-07-24 12:14
Same here. 

I try 12.x and got: https://rpm.nodesource.com/pub_12.x/el/7/x86_64/nodejs-10.22.0-1nodesource.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found

**Comment by benbcai** [comment] 2020-07-24 17:51
We also got this error yesterday. The error appears to be fixed temporarily yesterday but resurfaced again this morning. Is [nodejs-10.22.0-1nodesource.x86_64.rpm](https://rpm.nodesource.com/pub_10.x/el/7/x86_64/) that got released yesterday somehow got corrupted? We also cannot upgrade to node 12 at this time due to incompatibilities in our ecosystem.

**Comment by robskrob** [comment] 2020-07-25 16:20
I have a Amazon Linux 2 server in Virginia that successfully downloads nodejs 10.x as demonstrated above:
```
curl -sL https://rpm.nodesource.com/setup_10.x | bash -E
```

However, the Amazon Linux 2 server in Paris is experiencing the same error as indicated in the above issue. Perhaps the problem is regional. I also notice that @hbouhadji is based in France, adding more to my thinking that this failure to download is a regional problem.

**Comment by mattcharlton** [comment] 2020-07-25 17:10
Yeah we’re in the UK deploying to EU-West-2 so it does sound regional.

**Comment by mattcharlton** [comment] 2020-07-27 08:14
Still seeing this issue this morning, Not in EU-West-1.  Only in EU-West-2.

EU-West-1 doesn't have the Nodesource gpg key in place.  

EU-West-2 does, and fails.

I've found that If we run:

rm -f /etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL

prior to trying installation, this works.  Adjust your scripts using the above and hopefully it'll get you past the blocker whilst the issue with that key is resolved.  

I'll raise a support ticket with AWS as its obviously something on the AMI.

**Comment by hbouhadji** [comment] 2020-07-27 09:50
Look my first post @mattcharlton, with the docker image amazonlinux (you can try locally) there is not any NODESOURCE-GPG-SIGNING-KEY-EL file but still failing at the download of the package.
```
Downloading packages:
nodejs-10.22.0-1nodesource.x86 FAILED                                              53% [======================================                                  ]  0.0 B/s |  11 MB  --:--:-- ETA 
https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodejs-10.22.0-1nodesource.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=nodesource clean metadata
Trying other mirror.


Error downloading packages:
  2:nodejs-10.22.0-1nodesource.x86_64: [Errno 256] No more mirrors to try.
```

(I have a UK London IP)

**Comment by mattcharlton** [comment] 2020-07-27 09:53
> 
> 
> Look my first post @mattcharlton, with the docker image amazonlinux (you can try locally) there is not any NODESOURCE-GPG-SIGNING-KEY-EL file but still failing at the download of the package.
> 
> ```
> Downloading packages:
> nodejs-10.22.0-1nodesource.x86 FAILED                                              53% [======================================                                  ]  0.0 B/s |  11 MB  --:--:-- ETA 
> https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodejs-10.22.0-1nodesource.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=nodesource clean metadata
> Trying other mirror.
> 
> 
> Error downloading packages:
>   2:nodejs-10.22.0-1nodesource.x86_64: [Errno 256] No more mirrors to try.
> ```
> 
> (I have a UK London IP)

I replicated on a brand new EC2 instance in London, couldn't download the package, deleted the GPG key, was able to download and install the package.  

Spun up another one and replicated and tested the same.  Either way - I've logged a support request with AWS.

**Comment by mattcharlton** [comment] 2020-07-27 11:05
The more we look into this, the more it feels like an issue with an upstream mirror somewhere.  

Hit and miss as to whether it works or not.  

Still looking into things here - if I find something that definitely fixes it until whoever is responsible fixes it properly, I'll share.

**Comment by ryanthemanuel** [comment] 2020-07-27 19:05
Is there any update on this?  This is causing a fair amount of disruption to our builds (and we cannot currently upgrade to Node 12).

**Comment by mattcharlton** [comment] 2020-07-27 20:09
We ended up putting in an install of nodeJS 12 in the user data for the build ec2 instances. This means that node12 was already in place when node10 tries to install (and would fail) but as a newer version is already in place, it skips installation.  

Appreciate this won’t work for anyone who can’t upgrade to node 12 but we were lucky that our temporary ec2 instances we use for deployment had no dependencies. 

Other than this we found no reliable workaround as the issue was hit and miss.

**Comment by igsu** [comment] 2020-07-31 13:25
@hbouhadji can you confirm that this was stabilized?

**Comment by theherk** [comment] 2021-09-24 14:14
Looking like this is still present today with nodejs-16 in eu-west-1.

```sh
Downloading packages:
nodejs-16.10.0-1nodesource.x86 FAILED                                          
https://rpm.nodesource.com/pub_16.x/el/7/x86_64/nodejs-16.10.0-1nodesource.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=nodesource clean metadata
Trying other mirror.


Error downloading packages:
  2:nodejs-16.10.0-1nodesource.x86_64: [Errno 256] No more mirrors to try.
```

**Comment by novahyth** [comment] 2021-09-25 08:44
Same issue on my end (CentOS 7).

`Downloading packages:
No Presto metadata available for nodesource
nodejs-16.10.0-1nodesource.x86 FAILED                                          ========================================-      ]  10 MB/s |  28 MB  00:00:00 ETA
https://rpm.nodesource.com/pub_16.x/el/7/x86_64/nodejs-16.10.0-1nodesource.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=nodesource clean metadata
Trying other mirror.


Error downloading packages:
  2:nodejs-16.10.0-1nodesource.x86_64: [Errno 256] No more mirrors to try.`

**Comment by h3trika** [comment] 2021-09-28 11:08
Same issue on us-east-1

```
Downloading packages:
nodejs-16.10.0-1nodesource.x86 FAILED                                           
https://rpm.nodesource.com/pub_16.x/el/7/x86_64/nodejs-16.10.0-1nodesource.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=nodesource clean metadata
Trying other mirror.

Error downloading packages:
  2:nodejs-16.10.0-1nodesource.x86_64: [Errno 256] No more mirrors to try.
```

**Comment by ssc-boreus** [comment] 2021-09-30 07:41
Same issue with nodejs16 on eu-central-1 
```
Downloading packages:
nodejs-16.10.0-1nodesource.x86 FAILED
https://rpm.nodesource.com/pub_16.x/el/7/x86_64/nodejs-16.10.0-1nodesource.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=nodesource clean metadata
Trying other mirror.


Error downloading packages:
  2:nodejs-16.10.0-1nodesource.x86_64: [Errno 256] No more mirrors to try.
```

Yesterday it started working for some time, so I thought this issue was maybe fixed on the CDN. But today the issue appeared again.

**Comment by ssc-boreus** [comment] 2021-09-30 09:18
Additional note:
SHA256SUMS for nodejs v16.10.0 ( https://nodejs.org/dist/v16.10.0/ ) was signed by 4ED778F539E3634C779C87C6D7062848A1AB005C (Beth Griggs) which is valid but **EXPIRED** since 2021-03-25

**Closed** 2022-03-08 15:15 UTC
