### ISSUE TITLE
## Your distribution, identified as "fedora-release-28-1.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

### ISSUE THREAD

**Issue by jl91** [nodesource/distributions#656] opened 2018-05-03 19:12 UTC
➜  ~ curl --silent --location https://rpm.nodesource.com/setup_10.x | sudo bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "fc28-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_10.x/fc/28/x86_64/nodesource-release-fc28-1.noarch.rpm'

**Comment by chrislea** [comment] 2018-05-03 19:14
Duplicate of https://github.com/nodesource/distributions/issues/655, closing.

**Closed by chrislea** 2018-05-03 19:14 UTC
