### ISSUE TITLE
[ERROR] Node.js 16.x on Debian Bookworm Installation fail

### ISSUE THREAD

**Issue by hariso** [nodesource/distributions#1601] opened 2023-07-10 13:02 UTC
Before we come to the bug, thank you very much for this project! 

**Describe your bug**
Installing NodeJS 16 on Debian Bookworm gives `npm: command not found`.

**Distribution Information:**
 - OS: Debian
 - Version: Bookworm
 -  Docker image: `debian:bookworm-20230703`

**Node Version:**
 - Node: v16.x

**To Reproduce**
1. Install Debian Bookworm: `docker run -ti --rm debian:bookworm-20230703 /bin/bash`
2. Install Node.js v16.x using following instructions:
```bash
apt-get update && \
    apt-get install -y curl

curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get install -y nodejs && \
    npm update
```

**Expected behavior**
`npm` is correctly installed. Instead

**Screenshots**

**Additional context**
Same works on `debian:bullseye`.

**Comment by cuberinooo** [comment] 2023-07-15 14:38
Same here !

Out dockerfile looks like (NODE_VERSION=16):

```
RUN apt-get update \
    && curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g npm
```
    
  and we get the same error: "npm not found"
  
  As we work with php 8,1 we changed the node version to 18.x and it works.

**Comment by devin-purple** [comment] 2023-07-27 18:33
I'm seeing the same issue. Still have to use v16 for some things.

**Comment by o1y** [comment] 2023-08-12 10:32
[They can't reproduce this](https://github.com/nodesource/distributions/issues/1579#issuecomment-1594658955). As a workaround, you have to pin the `deb.nodesource.com` repository first, before running the setup script:

```Dockerfile
RUN echo "Package: nodejs" >> /etc/apt/preferences.d/preferences && \
    echo "Pin: origin deb.nodesource.com" >> /etc/apt/preferences.d/preferences && \
    echo "Pin-Priority: 1001" >> /etc/apt/preferences.d/preferences

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y nodejs
```

**Comment by JesusPaz** [comment] 2023-08-29 19:25
This issue is resolved with our new repository. More information can be found [here](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository).

**Comment by lightswitch05** [comment] 2023-08-31 15:17
Hello @JesusPaz @o1y - using the new repository does not fix this issue. Also, it is trivial to reproduce with a simple copy/paste command:

```bash
docker pull debian:bookworm-slim
docker build --progress=plain -t test-debian-proxy-with-system-certs:local -f- . <<EOF
FROM debian:bookworm-slim
RUN apt-get update \
    && apt-get install -y ca-certificates curl gnupg \
    && mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
    && apt-get update \
    && apt-get install -y nodejs
RUN npm install lodash
EOF
```

Node appears to install correctly - using the commands specificed by the new repository. However, the final `npm install` command fails with the same error this issue was opened with:

> /bin/sh: 1: npm: not found

Its also interesting that the same error occurs with node 18.  Also using debian bullseye. It just seems NPM is never installed using this method. Is that the expectation?

**Comment by JesusPaz** [comment] 2023-08-31 15:22
We will check it out and let you know if we have any news.

**Comment by lightswitch05** [comment] 2023-08-31 15:37
Actually, I would like to update my comment about bullseye - maybe something was going on with cache - but this works successfully with bullseye.

```bash
docker build --no-cache --progress=plain -t test-node-install:local -f- . <<EOF
FROM debian:bullseye-slim
WORKDIR /app
RUN apt-get update \
    && apt-get install -y ca-certificates curl gnupg \
    && mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
    && apt-get update \
    && apt-get install -y nodejs
RUN npm install lodash
EOF
```

The exact same commend with bullseye switched out to bookworm fails:

```bash
docker build --no-cache --progress=plain -t test-node-install:local -f- . <<EOF
FROM debian:bookworm-slim
WORKDIR /app
RUN apt-get update \
    && apt-get install -y ca-certificates curl gnupg \
    && mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
    && apt-get update \
    && apt-get install -y nodejs
RUN npm install lodash
EOF
```

**Comment by o1y** [comment] 2023-08-31 16:32
@lightswitch05 

This seems to be the same issue as before. You have to pin `deb.nodesource.com` first. Just an example:

```Bash
docker build --no-cache --progress=plain -t test-node-install:local -f- . <<EOF
FROM debian:bookworm-slim
WORKDIR /app
RUN apt-get update \
    && apt-get install -y ca-certificates curl gnupg \
    && mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
    && echo "Package: nodejs" >> /etc/apt/preferences.d/preferences \
    && echo "Pin: origin deb.nodesource.com" >> /etc/apt/preferences.d/preferences \
    && echo "Pin-Priority: 1001" >> /etc/apt/preferences.d/preferences\
    && apt-get update \
    && apt-get install -y nodejs

RUN npm install lodash
EOF
```

**Comment by dvdknaap** [comment] 2023-09-02 09:32
I had the same issue with node_20

it was indeed fixed with 

```dockerfile
RUN echo "Package: nodejs" >> /etc/apt/preferences.d/preferences \
    && echo "Pin: origin deb.nodesource.com" >> /etc/apt/preferences.d/preferences \
    && echo "Pin-Priority: 1001" >> /etc/apt/preferences.d/preferences
```

This only works with app resources.

```dockerfile

RUN mkdir -p /etc/apt/keyrings && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
```

Could you also add this update the setup files like `https://deb.nodesource.com/setup_20.x` because it's now installing a different version ?

In my case it was installing version 18 instead of 20

**Comment by diegocam** [comment] 2023-10-21 19:30
If you are specifying `NODE_MAJOR=16`, why do you have to pin it? Still seems like an issue that needs to be solved.

**Comment by diegocam** [comment] 2023-10-21 19:49
> We will check it out and let you know if we have any news.

@JesusPaz Any updates?

**Comment by Nardol** [comment] 2023-12-28 09:44
Could it be possible to provide E.G. `/etc/apt/preferences.d/nodejs` in the nodejs package to specify the repository to pin to?
And specify to install Nodejs by running `apt install nodejs/nodistro` in the documentation.
Best solution would be to make this configuration at the repository level I.E. as Debian backports repositories do.

**Comment by gremo** [comment] 2024-01-23 17:12
Same problem here (opened a new issue before looking at this... https://github.com/nodesource/distributions/issues/1770)

**Comment by riosje** [comment] 2024-01-23 20:00
The workaround to this is to use the `Pin-priority` in the repo.
```
echo "Pin: origin deb.nodesource.com" | tee -a /etc/apt/preferences.d/nodejs > /dev/null
echo "Pin-Priority: 600" | tee -a /etc/apt/preferences.d/nodejs > /dev/null
```

This config has to be done because the default debian and ubuntu repo has more priority than the nodesource repo.
The latest installation scripts has this config built-tin and this is not a problem any more to install the latest versions of nodejs.

**Closed by riosje** 2024-01-23 20:00 UTC
Labels: bug, waiting on response from NodeSource

**Comment by gremo** [comment] 2024-01-23 20:22
@riosje really thank you for your help, the official script works fine! So sorry not to read the updated readme.
