### ISSUE TITLE
[ERROR] Node.js 18/20 Lunar repo fetch fails with "Hash Sum mismatch"

### ISSUE THREAD

**Issue by yktoo** [nodesource/distributions#1587] opened 2023-06-22 07:41 UTC
**Describe your bug**

**Distribution Information:**
 - OS: Ubuntu
 - Version: 23.04 Lunar Lobster

**Node Version:**
 - Node: 20.x, 18.x

**To Reproduce**
1. Add the following to `/etc/apt/sources.list.d/nodesource.list`:
```
deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x lunar main
deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x lunar main
```
2. `sudo apt update`
3. The update fails with:

```
Err:18 https://deb.nodesource.com/node_20.x lunar/main amd64 Packages
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:777 [weak]
   - SHA256:d3f27ebc448d5904f92e83ab311460dbe7f3b1cd301b96e3272ad46f36bedcc5
   - SHA1:d5734eed42a52b07875d413076e72bfc9baf940e [weak]
   - MD5Sum:59e22e9983ba2434a056d4bfeb073938 [weak]
  Hashes of received file:
   - SHA256:95251e9ede1dbe3b8e931980e4f1d0b52cf2a8626785e77497360a495f72187d
   - SHA1:882b4e7579d7960b6a01a08551c5cdd0dd0cf60b [weak]
   - MD5Sum:e5d24a15e619cdb693f4ecbc666f8cdf [weak]
   - Filesize:777 [weak]
  Last modification reported: Wed, 21 Jun 2023 21:47:02 +0000
  Release file created at: Thu, 08 Jun 2023 21:03:29 +0000
Fetched 6.889 B in 1s (5.179 B/s)
Reading package lists... Done
E: Failed to fetch https://deb.nodesource.com/node_20.x/dists/lunar/main/binary-amd64/Packages.gz  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:777 [weak]
    - SHA256:d3f27ebc448d5904f92e83ab311460dbe7f3b1cd301b96e3272ad46f36bedcc5
    - SHA1:d5734eed42a52b07875d413076e72bfc9baf940e [weak]
    - MD5Sum:59e22e9983ba2434a056d4bfeb073938 [weak]
   Hashes of received file:
    - SHA256:95251e9ede1dbe3b8e931980e4f1d0b52cf2a8626785e77497360a495f72187d
    - SHA1:882b4e7579d7960b6a01a08551c5cdd0dd0cf60b [weak]
    - MD5Sum:e5d24a15e619cdb693f4ecbc666f8cdf [weak]
    - Filesize:777 [weak]
   Last modification reported: Wed, 21 Jun 2023 21:47:02 +0000
   Release file created at: Thu, 08 Jun 2023 21:03:29 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Expected behavior**
Package lists are successfully updated

**Additional context**
The same applies to the 18.x repository (didn't test earlier versions).

**Comment by morph027** [comment] 2023-06-22 09:05
Same here (of course ;) ) Looks like 16 is not affected (just tested)

**Comment by Facj** [comment] 2023-06-22 11:49
Same here for node for Node version 16.x and distribution Debian 9 stretch. 
I get the error but I'm still able to install nodejs afterwards. 

I've run the script several times today with different results:
- The error described in this issue
- Your distribution is no longer suported
- Everything ok

**Comment by dorianfm** [comment] 2023-06-23 09:33
I'm seeing similar errors for node 16 on Ubuntu 20.04.6 LTS (Focal Fossal) 

/etc/apt/sources.list.d:
```
deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x focal main
deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x focal main
```

`sudo apt update` outut

```
Get:12 https://deb.nodesource.com/node_16.x focal/main amd64 Packages [775 B]
Err:12 https://deb.nodesource.com/node_16.x focal/main amd64 Packages
  File has unexpected size (776 != 775). Mirror sync in progress? [IP: 2a02:26f0:fd00:3::213:7584 443]
  Hashes of expected file:
   - Filesize:775 [weak]
   - SHA256:0c6d8382f60bbb4bcc24ce922521673cd749c7530b2128b8dffb3e11297d1a15
   - SHA1:1e1b1951e616fb84373ee32a26944b356a83149d [weak]
   - MD5Sum:fdee69ee72123acebf6c975c753f6182 [weak]
  Release file created at: Wed, 21 Jun 2023 21:26:29 +0000
Fetched 4,583 B in 1s (5,096 B/s)
Reading package lists... Done
E: Failed to fetch https://deb.nodesource.com/node_16.x/dists/focal/main/binary-amd64/Packages.gz  File has unexpected size (776 != 775). Mirror sync in progress? [IP: 2a02:26f0:fd00:3::213:7584 443]
   Hashes of expected file:
    - Filesize:775 [weak]
    - SHA256:0c6d8382f60bbb4bcc24ce922521673cd749c7530b2128b8dffb3e11297d1a15
    - SHA1:1e1b1951e616fb84373ee32a26944b356a83149d [weak]
    - MD5Sum:fdee69ee72123acebf6c975c753f6182 [weak]
   Release file created at: Wed, 21 Jun 2023 21:26:29 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by Zenexer** [comment] 2023-06-23 14:38
Duplicate of #1576.  As a temporary workaround, sometimes using `http` instead of `https` works.

**Closed** 2023-06-27 15:55 UTC
Labels: bug
