### ISSUE TITLE
Package nodejs-18.3.0-1nodesource.x86_64.rpm is not signed

### ISSUE THREAD

**Issue by heitkergm** [nodesource/distributions#1405] opened 2022-06-02 21:56 UTC
This started today (6/2/2022).  running Fedora 36, and updating an existing install of nodejs 18...

**Comment by jknaus** [comment] 2022-06-03 12:28
I can confirm this also for Fedora 35 + nodejs18

**Comment by GeorgeDakhil** [comment] 2022-06-03 13:39
I have this fix > **Package nodejs-18.3.0-1nodesource.x86_64.rpm is not signed.**

Does anyone know how to solve?

**Comment by riosje** [comment] 2022-06-03 15:51
Hello guys, we're looking into this issue to fix it.
We expect this to be solved on the next release.

**Comment by ripsivis** [comment] 2022-06-03 17:01
use `--nogpgcheck` flag with dnf to skip gpg check temporarily

**Comment by SiqueiraX** [comment] 2022-06-07 03:28
same issue :(

**Comment by Zabrah** [comment] 2022-06-08 19:32
> use `--nogpgcheck` flag with dnf to skip gpg check temporarily

@ripsivis Is this secure to do? Did you made this and is everything working correctly?

**Comment by geosuna** [comment] 2022-06-13 17:57
> use `--nogpgcheck` flag with dnf to skip gpg check temporarily

it worked for me, thanks!

**Comment by jknaus** [comment] 2022-06-20 13:17
Seems to be fixed in 18.4.0

**Comment by riosje** [comment] 2022-06-20 19:11
Hello guys on the latests versions this issue has been fixed.

**Closed by riosje** 2022-06-20 19:11 UTC
Labels: help wanted
