### ISSUE TITLE
[ERROR] rpm.nodesource.com certificate expired

### ISSUE THREAD

**Issue by davemathews** [nodesource/distributions#1511] opened 2023-01-31 18:14 UTC
2023-01-31 17:52:31,765 [ERROR] Yum makecache failed. Output: Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
https://rpm.nodesource.com/pub_12.x/el/7/x86_64/repodata/repomd.xml: [Errno 14] curl#60 - "SSL certificate problem: certificate has expired"
Trying other mirror.
https://rpm.nodesource.com/pub_12.x/el/7/x86_64/repodata/4e3bfa1ccd2409a50a182bef2afafc8b33612d3b-filelists.sqlite.bz2: [Errno 14] curl#60 - "SSL certificate problem: certificate has expired"
Trying other mirror.
https://rpm.nodesource.com/pub_12.x/el/7/x86_64/repodata/ae56cfb4bd07597feffc06e6d0c1f06bed77681e-other.sqlite.bz2: [Errno 14] curl#60 - "SSL certificate problem: certificate has expired"

**Comment by JesusPaz** [comment] 2023-01-31 19:06
Duplicate of #1507

**Closed by JesusPaz** 2023-01-31 19:06 UTC
Labels: bug
