### ISSUE TITLE
Amazon Linux with Node 4.x

### ISSUE THREAD

**Issue by tellner** [nodesource/distributions#275] opened 2016-04-12 23:51 UTC
I started setting up node.js on an AWS instance and got the following:

```
$ sudo curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -

## Installing the NodeSource Node.js 4.x LTS Argon repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Could not determine your distribution version, you may not be running a supported version of Enterprise Linux. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect. Include your 'distribution package' name: system-release-2013.09-1.0.noarch. 
```
Is there a way of installing it with yum on a system of this vintage?

**Comment by tellner** [comment] 2016-04-12 23:55
Not sure how I missed this....
There's a [similar issue open](https://github.com/nodesource/distributions/issues/175) for a different version of Amazon Linux

**Comment by jborseth** [comment] 2016-05-23 20:06
Would be awesome to have NodeJS 6 install script (https://rpm.nodesource.com/setup_6.x) for Amazon Linux (based on CentOS, uses yum).

**Comment by retrohacker** [comment] 2016-06-06 19:29
Duplicate of https://github.com/nodesource/distributions/issues/175

Will continue tracking there :heart:

**Closed by retrohacker** 2016-06-06 19:29 UTC

**Comment by retrohacker** [comment] 2016-06-06 19:30
@jborseth that issue appears to be a permissions issue, not a problem with the installation script. When logged in as the user running the script, do you have access to /var/lib/rpm.rpm.lock ?
