### ISSUE TITLE
Your distribution, identified as "unknown.new.testing"

### ISSUE THREAD

**Issue by ahmedmhmdn** [nodesource/distributions#896] opened 2019-09-10 11:48 UTC
## Confirming "unknown.new.testing" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/unknown.new.testing/Release'

**Comment by igsu** [comment] 2019-12-27 20:45
The issue is not related to the NodeSource distributions support, but to the source distro (Codename `unknown.new.testing` is wrong). 

Closing this now.

**Closed by igsu** 2019-12-27 20:45 UTC
