### ISSUE TITLE
Fedora 28?

### ISSUE THREAD

**Issue by scottbert** [nodesource/distributions#660] opened 2018-05-07 04:27 UTC
```Your distribution, identified as "fedora-release-28-1.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support```

Are you considering supporting the latest Fedora?

**Comment by chrislea** [comment] 2018-05-07 04:42
Duplicate of https://github.com/nodesource/distributions/issues/655, closing.

**Closed by chrislea** 2018-05-07 04:42 UTC

**Comment by scottbert** [comment] 2018-05-07 04:45
IMHO #655 should be left open until then so you don't get loads of people opening a bug about Fedora 28 not being supported? Also it doesn't make much sense? Node 8.11.1 in Fedora 28 is definitely upgradeable to Node 10.x

**Comment by chrislea** [comment] 2018-05-07 04:50
From experience, we get loads of these things every time there's a new "important" distro release no matter what we do. C'est la vie. ¯\_(ツ)_/¯

The way that our build systems work for this make it rather annoying to go back and retroactively package previous releases for new distros, which is why we don't do it. I expect there will be a new 10.x release out this week and there will be FC28 targeted packages at that point. If you absolutely need a 10.x RPM right now, the [ones for FC27](https://rpm.nodesource.com/pub_10.x/fc/27/x86_64/) should work just fine.

Sorry for the hassle.
