### ISSUE TITLE
Ubuntu Budgie 22.04 LTS (Jammy Jellyfish)

### ISSUE THREAD

**Issue by joshxyzhimself** [nodesource/distributions#1359] opened 2022-03-27 06:24 UTC
> Your distribution, identified as "Ubuntu Jammy Jellyfish (development branch)", is a pre-release version of Ubuntu. NodeSource does not maintain official support for Ubuntu versions until they are formally released. You can try using the manual installation instructions available at https://github.com/nodesource/distributions and use the latest supported Ubuntu version name as the distribution identifier, although this is not guaranteed to work.

**Comment by gaby** [comment] 2022-04-20 03:48
Any updates on this? Ubuntu 22.04 is schedule to be released in 2 days (April 21, 2022).

**Comment by ZCShou** [comment] 2022-04-21 10:51
Ubuntu 22.04 has released

**Comment by JesusPaz** [comment] 2022-04-21 20:46
Changes to support Ubuntu 22.04 are already on our server. It is necessary to wait for a new Node.js version for the changes to be applied.

**Comment by MitchTalmadge** [comment] 2022-04-21 20:59
How long do you think it will be before there is an update?

**Comment by mwt** [comment] 2022-04-21 21:10
> How long do you think it will be before there is an update?

You can make a guess from this: https://github.com/nodejs/node/releases
Probably a week or two. They just did a major release two days ago.

**Comment by JesusPaz** [comment] 2022-04-21 21:42
I agree with @mwt.

There is also the option to install the packages manually by following our [README](https://github.com/nodesource/distributions#manual-installation).

**Comment by mwt** [comment] 2022-04-21 22:09
> There is also the option to install the packages manually by following our [README](https://github.com/nodesource/distributions#manual-installation).

It's a single package repo. So you could also just install the appropriate file from [this folder](https://deb.nodesource.com/node_18.x/pool/main/n/nodejs/) (probably [this one](https://deb.nodesource.com/node_18.x/pool/main/n/nodejs/nodejs_18.0.0-deb-1nodesource1_amd64.deb)). By the time you can update, the script will be working.

**Comment by holta** [comment] 2022-04-22 02:32
> There is also the option to install the packages manually by following our [README](https://github.com/nodesource/distributions#manual-installation).

Is the above suggestion expected to work?

Following the above instructions leads to this error message FYI:

```
$ sudo apt-get update
Get:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Hit:2 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:4 https://deb.nodesource.com/node_18.x jammy InRelease
Err:5 https://deb.nodesource.com/node_18.x jammy Release
  404  Not Found [IP: 23.44.133.12 443]
Hit:6 http://security.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
E: The repository 'https://deb.nodesource.com/node_18.x jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

(FYI 23.44.133.12 is pingable, which is just to confirm that this is not a network/connectivity issue.)

**Comment by mwt** [comment] 2022-04-22 02:34
No, you'd have to set it to one of the supported dists like focal instead of jammy.

**Comment by holta** [comment] 2022-04-22 02:58
> It's a single package repo. So you could also just install the appropriate file from [this folder](https://deb.nodesource.com/node_18.x/pool/main/n/nodejs/) (probably [this one](https://deb.nodesource.com/node_18.x/pool/main/n/nodejs/nodejs_18.0.0-deb-1nodesource1_amd64.deb)). By the time you can update, the script will be working.

Thanks &mdash; that seems to work:

```
$ sudo apt install ./nodejs_18.0.0-deb-1nodesource1_amd64.deb
...
N: Download is performed unsandboxed as root as file '/root/nodejs_18.0.0-deb-1nodesource1_amd64.deb' couldn't be 
accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
```

The above warning would appear to be harmless.  As indicated by:

```
$ apt list nodejs
Listing... Done
nodejs/now 18.0.0-deb-1nodesource1 amd64 [installed,local]

$ node -v
v18.0.0

$ npm -v
8.6.0

$ cat /etc/issue.net
Ubuntu 22.04 LTS
```

**Comment by LadyCharlotte** [comment] 2022-04-22 09:27
> I agree with @mwt.
> 
> There is also the option to install the packages manually by following our [README](https://github.com/nodesource/distributions#manual-installation).

I tried this manual installation - with out any luck. My /etc/apt/sources.list.d looks like this:

cat /etc/apt/sources.list.d/nodesource.list 
deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x focal main
deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x focal main

But I still get this error when doing an update:

Ign:1 https://deb.nodesource.com/node_18.x focal InRelease
Err:2 https://deb.nodesource.com/node_18.x focal Release                                                                                                                                                     
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 5.186.13.19 443]

I'm on WSL v1 on a windows 10 and suspecting this might be a root cause. A lsb_release -a gives me this:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

I need to update my node.js which is version v10.19.0

**Comment by akpatternica** [comment] 2022-04-22 09:32
@LadyCharlotte do you appy point 2 of "readme"

KEYRING=/usr/share/keyrings/nodesource.gpg
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | sudo tee "$KEYRING" >/dev/null
# wget can also be used:
# wget --quiet -O - https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | sudo tee "$KEYRING" >/dev/null
gpg --no-default-keyring --keyring "$KEYRING" --list-keys

**Comment by LadyCharlotte** [comment] 2022-04-22 09:40
@akpatternica 

from my bash history:

```bash
  550  curl -fsSLk https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | sudo tee "$KEYRING" >/dev/null
  551  gpg --no-default-keyring --keyring "$KEYRING" --list-keys
  552  VERSION=node_18.x
  553  KEYRING=/usr/share/keyrings/nodesource.gpg
  554  DISTRO="$(lsb_release -s -c)"
  555  echo "deb [signed-by=$KEYRING] https://deb.nodesource.com/$VERSION $DISTRO main" | sudo tee /etc/apt/sources.list.d/nodesource.list
  556  echo "deb-src [signed-by=$KEYRING] https://deb.nodesource.com/$VERSION $DISTRO main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list
  557  sudo apt-get update
```
As you might notice above, I always need to add the -k to curl to suppress the certificate-issue. I still need to figure out why and how to fix it.

By now, I downloaded the deb-package as suggested by @mwt above, and this seemed to work:

```bash
node --version
v18.0.0
```

But, I would still like to understand my certificate-issue. I constantly get this, also when updating other packages in /etc/apt/sources.list.d/

**Comment by seojustin** [comment] 2022-04-22 23:02
I'm running into this issue too, please take a look!!

`## Your distribution, identified as "jammy", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support`

**Comment by praveen-gm** [comment] 2022-04-23 05:49
I ran into the same issue, I installed it through nvm

`sudo apt install curl`

`curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash`

`source ~/.bashrc`

`nvm install 16.14.2`

**Comment by JukKie-ai** [comment] 2022-04-23 13:28
> > It's a single package repo. So you could also just install the appropriate file from [this folder](https://deb.nodesource.com/node_18.x/pool/main/n/nodejs/) (probably [this one](https://deb.nodesource.com/node_18.x/pool/main/n/nodejs/nodejs_18.0.0-deb-1nodesource1_amd64.deb)). By the time you can update, the script will be working.
> 
> Thanks — that seems to work:
> 
> ```
> $ sudo apt install ./nodejs_18.0.0-deb-1nodesource1_amd64.deb
> ...
> N: Download is performed unsandboxed as root as file '/root/nodejs_18.0.0-deb-1nodesource1_amd64.deb' couldn't be 
> accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
> ```
> 
> The above warning would appear to be harmless. As indicated by:
> 
> ```
> $ apt list nodejs
> Listing... Done
> nodejs/now 18.0.0-deb-1nodesource1 amd64 [installed,local]
> 
> $ node -v
> v18.0.0
> 
> $ npm -v
> 8.6.0
> 
> $ cat /etc/issue.net
> Ubuntu 22.04 LTS
> ```

thanks, this seems to work.

**Comment by oliverw** [comment] 2022-04-26 11:40
> Changes to support Ubuntu 22.04 are already on our server. It is necessary to wait for a new Node.js version for the changes to be applied.

That might be but that still does not help thousands of devs stuck on a major OS release without nodejs.

**Comment by jack1142** [comment] 2022-04-26 13:09
> That might be but that still does not help thousands of devs stuck on a major OS release without nodejs.

I would hope that there isn't *thousands* of devs who upgrade to new distro version not even a week since its release without first checking that their work environment won't be affected by it...

**Comment by oliverw** [comment] 2022-04-26 13:10
> > That might be but that still does not help thousands of devs stuck on a major OS release without nodejs.
> 
> I would hope that there isn't _thousands_ of devs who upgrade to new distro version not even a week since its release without first checking that their work environment won't be affected by it...

Was a fresh install of WSL2 on a fresh install of W11. No upgrade.

**Comment by soumith2105** [comment] 2022-04-28 01:41
It is working now.. I installed using
`curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -`
`sudo apt-get install -y nodejs`

**Comment by holta** [comment] 2022-04-28 01:59
Indeed, https://deb.nodesource.com/node_16.x/dists/jammy/Release is not like.

https://deb.nodesource.com/node_18.x/dists/jammy/Release not yet however.

**Comment by wkaluza** [comment] 2022-04-28 08:41
I was having this issue until recently. My usual way of installing Node in Ubuntu 20.04 Docker images was failing when I used an Ubuntu 22.04 base image. Things are now working on both Ubuntu versions (presumably thanks to the recent Node release?). Sharing the code below for completeness.

```
apt-get install --yes \
  curl

curl -fsSL "https://deb.nodesource.com/setup_lts.x" |
  bash -

apt-get install --yes \
  nodejs

npm config set ignore-scripts true --global
corepack enable
```

**Comment by abstractumx** [comment] 2022-04-29 20:40
Hello guys, 

still have same issue

```
Confirming "jammy" is supported...
curl -sLf -o /dev/null 'https://deb.nodesource.com/node_18.x/dists/jammy/Release'
Your distribution, identified as "jammy", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by mwt** [comment] 2022-04-29 20:43
> still have same issue

It will be fixed automatically at some point in the future. Please read above.

**Comment by GlassedSilver** [comment] 2022-05-02 09:13
I’m aware this may be a long shot, but: is version 12 going to get a 22.04 build?

**Comment by pashaiwnl** [comment] 2022-05-02 13:04
```bash
sudo curl -LO https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz
sudo tar -xvf node-v18.0.0-linux-x64.tar.xz
sudo cp -r node-v18.0.0-linux-x64/{bin,include,lib,share} /usr/
node --version # => v18.0.0
```

**Comment by Hunter-XD** [comment] 2022-05-03 07:22
When distribution support will come ?

**Comment by holta** [comment] 2022-05-03 14:08
> Indeed, https://deb.nodesource.com/node_16.x/dists/jammy/Release is now live.
> 
> https://deb.nodesource.com/node_18.x/dists/jammy/Release not yet however.

FYI https://nodejs.org/en/blog/release/v18.1.0/ = https://github.com/nodejs/node/releases/tag/v18.1.0 was released a couple hours ago.

This suggests Node.js 18.x support via nodesource.com for Ubuntu 22.04 will (probably!) be mainlined very shortly in coming days.

**Comment by JesusPaz** [comment] 2022-05-03 16:01
It is now possible to install Node.js v18 on Ubuntu 22.04

**Closed by JesusPaz** 2022-05-03 16:01 UTC
Labels: waiting on response from NodeSource, distribution support

**Comment by zzantares** [comment] 2022-05-03 16:34
@JesusPaz will earlier Node.js releases be supported? as an example we need Node.js v14 for Ubuntu 22.04, but it is not there still: https://deb.nodesource.com/node_14.x/dists/

**Comment by dmlyons** [comment] 2022-05-03 16:50
The script is still failing because https://deb.nodesource.com/node_18.x/dists/jammy/Release returns a 404.

**Comment by damousys** [comment] 2022-05-03 22:39
18.x also has an release file

**Comment by bci24** [comment] 2022-05-04 11:00
when install node 18 

```
sudo apt-get install -y nodejs
```

it return this error:

```
Preparing to unpack .../nodejs_18.1.0-deb-1nodesource1_amd64.deb ...
Unpacking nodejs (18.1.0-deb-1nodesource1) ...
dpkg: error processing archive /var/cache/apt/archives/nodejs_18.1.0-deb-1nodesource1_amd64.deb (--unpack):
 trying to overwrite '/usr/share/systemtap/tapset/node.stp', which is also in package libnode72:amd64 12.22.9~dfsg-1ubuntu3
Errors were encountered while processing:
 /var/cache/apt/archives/nodejs_18.1.0-deb-1nodesource1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by kousu** [comment] 2022-08-19 21:54
I got the same error for node 18 on Ubuntu 22.04. But I fixed it like this:

```
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt-get -o "Dpkg::Options::=–force-overwrite" install -y nodejs
sudo apt-get autoremove   # cleans up libnode72
```
