### ISSUE TITLE
Ubuntu 17.10 support

### ISSUE THREAD

**Issue by jayfoad** [nodesource/distributions#543] opened 2017-10-23 08:15 UTC
Please can you add support for Ubuntu 17.10 (Artful Aardvark) ? Currently I get:

```
$ curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

## Installing the NodeSource Node.js v8.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 http://security.ubuntu.com/ubuntu artful-security InRelease
Hit:2 http://gb.archive.ubuntu.com/ubuntu artful InRelease                                                                                                                                   
Hit:3 http://gb.archive.ubuntu.com/ubuntu artful-updates InRelease                                                                                                                           
Hit:4 http://gb.archive.ubuntu.com/ubuntu artful-backports InRelease                                                                                                                         
Hit:5 https://repo.skype.com/deb stable InRelease                                                                                                                                            
Get:6 http://gb.archive.ubuntu.com/ubuntu artful-proposed InRelease [235 kB]                                                                                                            
Hit:7 http://archive.canonical.com artful InRelease                                                                                                                                          
Ign:8 https://deb.nodesource.com/node_7.x artful InRelease                                                                    
Err:9 https://deb.nodesource.com/node_7.x artful Release                     
  404  Not Found [IP: 2600:9000:201f:e600:1f:6523:6040:93a1 443]
Reading package lists... Done
E: The repository 'https://deb.nodesource.com/node_7.x artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Error executing command, exiting
```

**Comment by Publish-Interactive** [comment] 2017-10-23 12:30
Duplicate of [#541](https://github.com/nodesource/distributions/issues)? I.e. I don't think this is specific to 17.10

**Comment by chrislea** [comment] 2017-10-23 16:37
Node 7.x is EOL and we're not making any new packages for it. If you use the setup script for 8.x, you'll find that artful is supported.

**Closed by chrislea** 2017-10-23 16:37 UTC

**Comment by jayfoad** [comment] 2017-10-24 10:06
Yup, 8.x works for me. Thanks.

**Comment by webolla** [comment] 2018-03-27 14:20
Please can you add support for Ubuntu 17.10 (Artful Aardvark). I have the same trouble

**Comment by proxycheck** [comment] 2018-04-21 17:27
I am also unable to get it to work on Ubuntu 17.10. This is the error I get:

E: The repository 'cdrom://Ubuntu-Server 17.10 _Artful Aardvark_ - Release amd64 (20180108.1) artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Error executing command, exiting
