### ISSUE TITLE
[ERROR] Node.js on Linux Mint Installation fail

### ISSUE THREAD

**Issue by Ro0ul** [nodesource/distributions#1607] opened 2023-07-19 12:21 UTC
![image](https://github.com/nodesource/distributions/assets/137962972/1ba349c2-725d-4232-9655-70345267935a)

**Comment by Iashvili27** [comment] 2023-07-19 14:54
I have the same problem..  Just installed Linux mint and can't install node.

**Comment by JesusPaz** [comment] 2023-07-19 15:07
Duplicate of #1603

**Closed by JesusPaz** 2023-07-19 15:07 UTC
Labels: bug
