### ISSUE TITLE
Node 12 LTS for Ubuntu 18.04 LTS Bionic Beaver 32 bits

### ISSUE THREAD

**Issue by sebma** [nodesource/distributions#1342] opened 2022-01-11 20:54 UTC
Hi,

How can I install nodejs >= 12  for Ubuntu 18.04 LTS Bionic Beaver 32 bits, there seem to be no package for it  : 
```bash
$ curl -s https://deb.nodesource.com/node_12.x/dists/bionic/main/binary-i386/Packages | grep Package:
$
```
?

**Comment by JesusPaz** [comment] 2022-01-25 19:55
Duplicate of #890

**Closed by JesusPaz** 2022-01-25 19:55 UTC
