### ISSUE TITLE
How should specific versions of node be used?

### ISSUE THREAD

**Issue by mmase** [nodesource/distributions#880] opened 2019-08-05 16:18 UTC
Over the course of the last 6 months, there have been 3 occasions where node versions were either deleted or slightly renamed. The most recent occurrence was over the weekend when `10.16.0-1nodesource1` was quietly deleted in favor of `10.16.1-1nodesource1`.

Is specifying `10.16.0-1nodesource1` too specific? Is there a better way to do this?

**Comment by JesusPaz** [comment] 2021-12-28 14:25
Duplicate of #33

**Closed by JesusPaz** 2021-12-28 14:25 UTC
