### ISSUE TITLE
Fedora 28

### ISSUE THREAD

**Issue by ai** [nodesource/distributions#661] opened 2018-05-07 15:01 UTC
Fedora 28 was released. We need to add support.

`fc27` repo works fine. So we just need to add addition number to install script and create a directory `fc28`.

@chrislea

**Comment by chrislea** [comment] 2018-05-07 15:50
Duplicate of https://github.com/nodesource/distributions/issues/655, closing.

**Closed by chrislea** 2018-05-07 15:50 UTC
