### ISSUE TITLE
bad interpreter: Permission not granted

### ISSUE THREAD

**Issue by belallioui** [nodesource/distributions#1001] opened 2020-01-27 11:00 UTC
Hi, 
To install nodeJs I executed the command 
 `curl -sL https://deb.nodesource.com/setup_13.x | sudo bash -`
Result : 
`## Installing the NodeSource Node.js 13.x repo...

## Populating apt-get cache...

+ apt-get update
Ign:1 http://deb.debian.org/debian stretch InRelease
Atteint:2 http://security.debian.org stretch/updates InRelease
Atteint:3 http://deb.debian.org/debian stretch-updates InRelease
Atteint:4 http://deb.debian.org/debian stretch Release
Atteint:5 http://apt.postgresql.org/pub/repos/apt stretch-pgdg InRelease
Atteint:6 https://deb.nodesource.com/node_9.x stretch InRelease
Lecture des listes de paquets... Fait
main: /usr/bin/lsb_release : /usr/bin/python3 : mauvais interpréteur: Permission non accordée
main: /usr/bin/lsb_release : /usr/bin/python3 : mauvais interpréteur: Permission non accordée

## Confirming "" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_13.x/dists//Release'

## Your distribution, identified as "", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
`

Thanks for your help

**Comment by igsu** [comment] 2020-01-28 13:43
Hi @belallioui,

Unfortunately the issue is not related to the NodeSource distributions support, but to the source distro (Codename "" is wrong).

Closing this now.

**Closed by igsu** 2020-01-28 13:43 UTC

**Comment by igsu** [comment] 2020-01-28 14:26
Your distribution is not returning anything from the command `lsb_release -c` and the setup script uses it to allow the installation or not. I recommend you to try manual instructions.
