### ISSUE TITLE
Fail to install nodejs 6.x/8.x for debian jessie

### ISSUE THREAD

**Issue by Marksion08** [nodesource/distributions#532] opened 2017-09-25 02:39 UTC
I tried to install nodejs 6.x/8.x for debian 8, after followed many way to, but this problem still.
It showed me as below:

## Confirming "jessie" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/jessie/Release'

## Your distribution, identified as "jessie", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

BTW: debian 8 jessie was download from the official-side.

PLS tell me if there was any wrong, I was fresh in Debian.
Thanks & Regards,
Marksion

**Comment by wolfflow** [comment] 2017-09-26 16:46
Got the same thing with **wheezy**. 
`Your distribution, identified as "wheezy", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support`

**Comment by rajudev** [comment] 2017-10-01 07:01
This issue is affecting me as well for Debian Jessie. 
`root@debian-jessie:~# curl -sL https://deb.nodesource.com/setup_8.x | bash -

## Installing the NodeSource Node.js v8.x repo...


## Populating apt-get cache...

+ apt-get update
Ign:1 http://deb.debian.org/debian jessie InRelease                                                               
Hit:2 http://deb.debian.org/debian jessie-updates InRelease                  
Hit:3 http://deb.debian.org/debian jessie Release                                                      
Get:5 https://apache.bintray.com/couchdb-deb jessie InRelease                                          
Ign:5 https://apache.bintray.com/couchdb-deb jessie InRelease
Hit:6 https://apache.bintray.com/couchdb-deb jessie Release
Hit:8 http://security.debian.org jessie/updates InRelease
Reading package lists... Done

## Confirming "n/a" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/n/a/Release'

## Your distribution, identified as "n/a", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

root@debian-jessie:~# 
`

**Comment by rajudev** [comment] 2017-10-01 07:03
Same issues with 7.x or 6.x release

**Comment by rajudev** [comment] 2017-10-01 09:23
Apparently I have found a solution for this. 
Do not use the nodesource script for this. Instead do manually what the script tries to do automatically. 

For your particular version of Debian/Ubuntu add the respective line to your sources.list file 
release name can be any of [these](https://deb.nodesource.com/node_8.x/dists/)
`
deb https://deb.nodesource.com/node_8.x/ <release name> main
`
add the repository key 
`curl --silent https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -`
and then do `apt update` and `apt install nodejs`

Let me know, if this was helpful to you. Thanks

**Comment by ARET-METAL** [comment] 2017-10-06 15:48
Buenas tardes a mi me presenta el mismo error que a ustedes y no me soluciona lo que recomendaste rajudev

**Comment by rajudev** [comment] 2017-10-06 18:53
@ARET-METAL Apologies,I don't understand your language. Would be great if you can repeat the message in English.

**Comment by ARET-METAL** [comment] 2017-10-06 19:01
I'm having problems installing taiga in debian jessie in dependencies and nodejs they will have an installation manual, thanks

**Comment by ARET-METAL** [comment] 2017-10-06 19:03
npm -v
ERROR: npm is known not to run on Node.js v0.10.29
You'll need to upgrade to a newer version in order to use this
version of npm. Supported versions are 4, 6, 7, 8. You can find the
latest version at https://nodejs.org/

**Comment by rajudev** [comment] 2017-10-09 07:27
@ARET-METAL Have you resolved your issue within the last three days? If it is still there I can still help.

**Comment by rajudev** [comment] 2017-10-09 07:29
@ARET-METAL Since you are already having npm installed, although an older version. 
You can just do `sudo npm install -g npm` to update your current version of npm

**Comment by Marksion08** [comment] 2017-10-10 01:55
@rajudev While tried to added responsitory key the errors showed: "gpg: no valid OpenPGP data found."
Should I need to install something?

**Comment by rajudev** [comment] 2017-10-10 07:17
@Marksion08 You need add the the keys for the repository. 
do `curl --silent https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -` 
hopefully this should solve your issue.

**Comment by JoSchmutz** [comment] 2017-10-10 08:24
Hi,
make sure your machine clock is set at the right time and date. That was the problem for me: 
date --set YEAR-MONTH-DATE

**Comment by krokofant** [comment] 2017-10-24 12:50
Expanding on @JoSchmutz solution is to make sure that the RPis datetime is updated automatically:
```sudo apt-get install ntpdate``` and restart and try again

**Comment by kenshinji** [comment] 2017-11-03 01:44
Same issue here, I installed nodejs **v0.10.29** through `sudo apt-get install nodejs` after I tried `curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -`, I was intend to install the latest version though.

**Comment by chrislea** [comment] 2017-11-03 01:55
I think the problem is you're passing the `-E` flag to `sudo` and not `bash`. Can you please try the following:
```
curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -E -
sudo apt-get install nodejs
```
and let us know what happens?

**Comment by kenshinji** [comment] 2017-11-03 04:45
@chrislea it doesn't work :(

**Comment by chrislea** [comment] 2017-11-03 04:59
@kenshinji okay can you please run
```
curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -E -x -
```
and past the full output here? Thanks.

**Comment by JoSchmutz** [comment] 2017-11-03 13:23
You should run
sudo date --set 17-11-03
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
Then
sudo apt install nodejs

**Comment by jo-argon7** [comment] 2017-11-03 14:51
I've just (re)done the installation on Debian jessie and it does not work !! bad version of node and unable to run npm !!

`***# date
vendredi 3 novembre 2017, 15:44:38 (UTC+0100)
***# apt install nodejs
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Les NOUVEAUX paquets suivants seront installés :
  nodejs
0 mis à jour, 1 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de prendre 0 o/12,7 Mo dans les archives.
Après cette opération, 61,0 Mo d'espace disque supplémentaires seront utilisés.
Sélection du paquet nodejs précédemment désélectionné.
(Lecture de la base de données... 36125 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../nodejs_8.9.0-1nodesource1_amd64.deb ...
Dépaquetage de nodejs (8.9.0-1nodesource1) ...
Traitement des actions différées (« triggers ») pour man-db (2.7.0.2-5) ...
Paramétrage de nodejs (8.9.0-1nodesource1) ...
***# node -v
v0.6.5
***# npm -v

/usr/lib/node_modules/npm/lib/utils/unsupported.js:27
        console.error(`a bug known to break npm. Please update to at least ${r
                      ^

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:427:25)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/lib/node_modules/npm/bin/npm-cli.js:92:2)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)`

**Comment by JoSchmutz** [comment] 2017-11-03 15:02
@jo-argo7 did you do 
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - 
Before runing apt install nodejs?

**Comment by JoSchmutz** [comment] 2017-11-03 15:04
@jo-argon7 make sure you are on jessie image and not stretch

**Comment by jo-argon7** [comment] 2017-11-03 15:04
yep, result is in /etc/apt/sources.list.d/nodesource.list
`deb https://deb.nodesource.com/node_8.x jessie main
deb-src https://deb.nodesource.com/node_8.x jessie main
`

**Comment by jo-argon7** [comment] 2017-11-03 15:07
Debian Jessie confirmed:
`***# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
`

**Comment by JoSchmutz** [comment] 2017-11-03 15:09
What do you get with that:

curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -

**Comment by jo-argon7** [comment] 2017-11-03 15:31
I've found another method and it works:
`# curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash
... open new shell ...
# command -v nvm  ... should output "nvm" ...
# nvm install node
`
and now everything's ok:
`# node -v
v9.0.0
# npm -v
5.5.1
`

**Comment by chrislea** [comment] 2017-11-03 17:23
Again, please run **exactly**:
```
curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -E -x -
```
and paste the full output here. This may help me see what's going on with the installer script.

**Comment by jo-argon7** [comment] 2017-11-03 19:59
output saved in file:
[nodesource.installer8.log](https://github.com/nodesource/distributions/files/1442337/nodesource.installer8.log)

**Comment by LC43** [comment] 2017-12-04 01:41
i'm on debian 9 and had the same "n/a" error :
```
## Confirming "n/a" is supported...
+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/n/a/Release'

## Your distribution, identified as "n/a", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

even tho

$cat /etc/debian_version 
```
9.0
```
and
$cat /etc/os-release 
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
[..]
```

so i followed @rajudev advice and added 
$cat /etc/apt/sources.list.d/nodesource.list
```
deb https://deb.nodesource.com/node_8.x jessie main
deb-src https://deb.nodesource.com/node_8.x jessie main
```
and

```
curl --silent https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
```

Did 

```
apt-get update
```

and finished with 
```
apt-get install nodejs
```

So now:

```
$node -v
v8.9.1
```

**Comment by jasompi** [comment] 2017-12-24 23:48
This is because the script use lsb_release to determine the codename. 

DISTRO=$(lsb_release -c -s)

However, on my Raspbian, lsb_release -c show:
Codename:	n/a

I fixed it by download the setup_9.x and manually change the line to:

DISTRO=jessie

**Comment by fabpin** [comment] 2018-09-16 21:01
Im on debian 8, in Deepin 15.07 64bits and have the same error, when write "npm -v", show thw following issue: bash: npm didn't found the order

**Comment by evictor** [comment] 2019-02-04 23:11
> Expanding on @JoSchmutz solution is to make sure that the RPis datetime is updated automatically:
> `sudo apt-get install ntpdate` and restart and try again

This worked for me.

**Comment by igsu** [comment] 2019-12-17 14:30
This has ben fixed a while ago.
Closing now.

**Closed by igsu** 2019-12-17 14:30 UTC
