### ISSUE TITLE
NodeJs for Ubuntu 22.04 LTS (Jammy)

### ISSUE THREAD

**Issue by romeujr** [nodesource/distributions#1376] opened 2022-04-21 19:35 UTC
Hello,

I was using the official release of Ubuntu 22.04 (ubuntu-jammy-oci-amd64-root.tar.gz), from:
https://partner-images.canonical.com/oci/jammy/current/

And I did run the command below:
curl -fsSL https://deb.nodesource.com/setup_16.x | bash -

And then I got this message:
## Your distribution, identified as "jammy", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

Could you please review this and update it?
Sorry for reporting this so early.

**Comment by JesusPaz** [comment] 2022-04-21 20:37
The changes to support Ubuntu 22.04 are already on our server. It is necessary to wait for a new Node.js version for the changes to be applied.

**Comment by JesusPaz** [comment] 2022-04-21 20:50
Duplicate of #1359

**Closed by JesusPaz** 2022-04-21 20:50 UTC
Labels: waiting on response from NodeSource, distribution support

**Comment by romeujr** [comment] 2022-04-22 10:40
Thank you!
