### ISSUE TITLE
Unable to install Node 16.17 on Amazon Linux 2

### ISSUE THREAD

**Issue by jamesalfei** [nodesource/distributions#1431] opened 2022-08-17 09:52 UTC
I raised an issue on the NodeJS GitHub repo but i'm unsure as to whether it would be more suitable to raise this issue here.

https://github.com/nodejs/node/issues/44260

# Version
16.17.0

# Platform
Linux e5669dcb775f 5.10.104-linuxkit https://github.com/nodejs/node/pull/1 SMP Thu Mar 17 17:08:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# Subsystem
No response

# What steps will reproduce the bug?
Dockerfile containing the following:

```dockerfile
FROM maven:3.8-amazoncorretto-11

RUN curl -fsSL https://rpm.nodesource.com/setup_16.x | bash -
RUN yum -y install nodejs
RUN npm -v
```

# How often does it reproduce? Is there a required condition?
Every time I try to install NodeJS via Yum

# What is the expected behavior?
NodeJS installs

# What do you see instead?
Transaction Summary
Install 1 Package

Total download size: 32 M
Installed size: 89 M
Downloading packages:
https://rpm.nodesource.com/pub_16.x/el/7/x86_64/nodejs-16.17.0-1nodesource.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=nodesource clean metadata
Trying other mirror.

Error downloading packages:
2:nodejs-16.17.0-1nodesource.x86_64: [Errno 256] No more mirrors to try.

# Additional information
I have tried the suggested fix of running yum --enablerepo=nodesource clean metadata prior to yum install vbut this does not resolve the issue.

**Comment by spike008t** [comment] 2022-08-17 11:19
Same issue, I have to force nodejs version to `16.16.0` (eg: `yum install node-16.16.0`)

**Comment by JesusPaz** [comment] 2022-08-17 11:40
Duplicate of #1290

**Closed by JesusPaz** 2022-08-17 11:40 UTC
Labels: duplicate
