### ISSUE TITLE
The installation script doesn't work correctly on Ubuntu 16.04 LTS. When the user intends to install v6, v4 is actually installed. 

### ISSUE THREAD

**Issue by x-ji** [nodesource/distributions#361] opened 2016-09-20 09:22 UTC
As documented at http://askubuntu.com/questions/786272/why-does-installing-node-6-x-on-ubuntu-16-04-actually-install-node-4-2-6, apparently there's some error in node installation script and when the user intends to install Node v6 on Ubuntu 16.04 LTS, v4 is actually installed. One has to manually add the NodeJS entry in `sources.list.d` for the installation to work.

Although that question on StackExchange was asked in June, I'm surprised to still encounter the same error, three months later. Seems that nobody filed a bug report.

---

## Reproduction steps:

Run

```
url -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs 
sudo apt-get install -y npm
```

on Ubuntu 16.04 LTS

---

## Actual results: Node v4.2.6 gets installed from the mainline repo

--

##Output of the script:

```
## Installing the NodeSource Node.js v6.x repo...


## Populating apt-get cache...

+ apt-get update

... Output from apt-get update, which doesn't show any abnormality
```

I don't see what other output can the user reasonably provide. Of course the answer in the post just says "the installer script didn't do what it's supposed to do", because it reports everything is normal and then boom, nothing works!

The question is upvoted 17 times on StackExchange. I and the OP are certainly not the only ones impacted by it.

Why doesn't somebody from the nodesource team actually try it out on Ubuntu 16.04 LTS and see if they can reproduce the issue as described instead of just closing the issue https://github.com/nodesource/distributions/issues/358 reported without even looking at it? It's not like 17 people just pop out of nowhere upvoting posts for fun. This is a quite insidious issue, since no error message is ever shown, a user might well expect Node v6 to be installed, only to face a load of issues later on. And I don't believe users of Ubuntu 16.04 LTS to be exactly a minority either.

**Comment by mweagle** [comment] 2016-09-20 13:37
Hello @x-ji,
Thanks for reporting this. We're not able to reproduce the specific problem you're running into, however there are diagnostic steps that should help identify the issue.

1. Download the https://deb.nodesource.com/setup_6.x install script: `curl https://deb.nodesource.com/setup_6.x -O`
2. Run the script: `sudo ./setup_6.x`
3. Check for any errors
4. Verify the sources list: `less /etc/apt/sources.list.d/nodesource.list`
5. Update: `sudo apt-get update`
6. Check for any errors
7. Verify the node v6 is available: `apt-cache policy nodejs`

Please update this issue with your findings. Thanks.

**Comment by chrislea** [comment] 2016-09-20 17:22
Closing this as I've re-opened #358 which is where this should get tracked, and this is now a dupe.

**Closed by chrislea** 2016-09-20 17:22 UTC
