### ISSUE TITLE
NodeJS 4.x support on CentOS 6

### ISSUE THREAD

**Issue by st-isidore-de-seville** [nodesource/distributions#181] opened 2015-11-23 20:07 UTC
If I am reading the documentation correctly, NodeJS 4.x and NodeJS 0.12 should be supported for CentOS 6.  When executing the appropriate curl bash commands, I am receiving the following error message:

```
[root@dnovips227 vagrant]# curl -sL https://rpm.nodesource.com/setup_4.x | bash -

## Installing the NodeSource Node.js 4.x repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release
+ uname -m

## Confirming "el6-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_4.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'

## Your distribution, identified as "centos-release-6-7.el6.centos.12.3.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

[root@dnovips227 vagrant]# curl -sL https://rpm.nodesource.com/setup_0.12 | bash -

## Installing the NodeSource Node.js 0.12 repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release
+ uname -m

## Confirming "el6-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_0.12/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'

## Your distribution, identified as "centos-release-6-7.el6.centos.12.3.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

[root@dnovips227 vagrant]# 
```

**Comment by OmerHerera** [comment] 2015-11-24 13:19
I know that I'm waiting for RPM for centOS 6(currently not supported :cry:), you can take a look to the [issue](https://rpm.nodesource.com/pub_4.x/el/6/x86_64/)

**Comment by st-isidore-de-seville** [comment] 2015-11-24 14:28
Yeah so it appears like that there is a problem with the script ....

**Comment by elabrc** [comment] 2015-12-15 16:47
I am also having this issue:

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_0.12/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'

## Your distribution, identified as "centos-release-6-7.el6.centos.12.3.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by devanes** [comment] 2015-12-17 14:38
It's not a problem with the script (for 4.x), the files for centos 6 just aren't there:
See: https://rpm.nodesource.com/pub_4.x/el/
There seem to be files there for Fedora though.

Please provide 4.x files for Centos/RHEL 6 as well!

**Comment by chrislea** [comment] 2015-12-17 18:39
This is effectively a dupe of #128. We don't have newer versions of Node for old distros currently due to compiler toolchain issues we're working to get around. Please see there for more info.

**Closed by chrislea** 2015-12-17 18:39 UTC
