### ISSUE TITLE
"fedora-release-28-1.noarch", is not currently supported

### ISSUE THREAD

**Issue by xorz57** [nodesource/distributions#658] opened 2018-05-05 14:09 UTC
```bash
[georgefotopoulos@localhost ~]$ curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -

## Installing the NodeSource Node.js 8.x LTS Carbon repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "fc28-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_8.x/fc/28/x86_64/nodesource-release-fc28-1.noarch.rpm'

## Your distribution, identified as "fedora-release-28-1.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

[georgefotopoulos@localhost ~]$ 
```

**Comment by chrislea** [comment] 2018-05-05 16:27
Duplicate of https://github.com/nodesource/distributions/issues/655, closing.

**Closed by chrislea** 2018-05-05 16:27 UTC
