### ISSUE TITLE
Fedora 19 support

### ISSUE THREAD

**Issue by gheist** [nodesource/distributions#609] opened 2018-02-08 16:42 UTC
Per https://nodejs.org/en/download/package-manager/ 
Supported Fedora versions:
Fedora 21 (Twenty One) (32-bit and 64-bit)
Fedora 20 (Heisenbug) (32-bit and 64-bit)
Fedora 19 (Schrödinger's Cat) (32-bit and 64-bit)

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_8.x/fc/19/i386/nodesource-release-fc19-1.noarch.rpm'

## Your distribution, identified as "fedora-release-19-8.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by chrislea** [comment] 2018-02-08 17:08
Sorry, but that page from nodejs.org is outdated. Please reference [the distributions page](https://github.com/nodesource/distributions/) directly.

Closing as dupe of #588.

**Closed by chrislea** 2018-02-08 17:08 UTC
