### ISSUE TITLE
NodeJS 16 is listed as "supported" in README but no instructions

### ISSUE THREAD

**Issue by evgeni** [nodesource/distributions#1749] opened 2024-01-03 09:04 UTC
**Describe your bug**
The README still lists NodeJS 16 as supported, but there are no instructions how to install it, and there are no "new" scripts for 16 in https://github.com/nodesource/distributions/tree/master/scripts either.

Additionally, the 18+ packages were signed with a new key for Red Hat family distros, but the 16.x ones that are still available in the "nodistro" repository use the old key.

**Expected behavior**
If a version is supported, there should be instructions/scripts how to install it, and it should be using the right signing key etc

**Comment by gwhizofss** [comment] 2024-01-10 19:13
Yes and see the later issue for more details also about 16.x

**Comment by ca-roshan** [comment] 2024-01-12 09:40
This might help, Got this from previous readme, this works now, but if they have removed from it, it might not work later,

> sudo apt-get update
sudo apt-get install -y ca-certificates curl gnupg
mkdir -p /etc/apt/keyrings
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

> NODE_MAJOR=16
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

> sudo apt-get update
sudo apt-get install nodejs -y

**Comment by JesusPaz** [comment] 2024-01-15 16:45
Duplicate of #1753

**Closed by JesusPaz** 2024-01-15 16:45 UTC
Labels: bug
