### ISSUE TITLE
Please add support for Ubuntu 19.10 (Eoan Ermine)

### ISSUE THREAD

**Issue by rakanskiy** [nodesource/distributions#918] opened 2019-10-14 09:55 UTC
Please consider to add upcoming Ubuntu release

**Comment by umpierrefp** [comment] 2019-10-17 18:41
Specially relevant now that it is officially released.

**Comment by christopherMills** [comment] 2019-10-17 21:58
Really relevant.

**Comment by carlosSoto2** [comment] 2019-10-17 23:23
extremely relevant

**Comment by pksasso** [comment] 2019-10-18 03:47
Really important.

**Comment by Georgebillion** [comment] 2019-10-18 10:13
extremely relevant

**Comment by AnnigilatorKM** [comment] 2019-10-18 22:03
Please add support for Ubuntu 19.10, really important

**Comment by vadimfrolov** [comment] 2019-10-19 11:20
lease add support for Ubuntu 19.10

**Comment by maximal** [comment] 2019-10-19 11:34
+1

**Comment by christian-ehmke** [comment] 2019-10-19 11:37
Please add support for Ubuntu 19.10, really important.

**Comment by Developer-Devansh** [comment] 2019-10-19 12:38
Please add the support for Ubuntu 19.10 Eoan Ermine. We're are requiring node to build a back-end, and it's not being downloaded.

**Comment by Jav3k** [comment] 2019-10-19 15:25
@Developer-Devansh, you can download latest version from https://nodejs.org/en/download/current/

or you can temporarily install nodejs snap package
```
snap install node --classic --channel=12
```
but snap is not recommended for production deployments

**Comment by imsmit** [comment] 2019-10-21 02:35
I installed nodejs using snap, & rest is working good for channel=10. But I'm getting EACCESS error for any command I pass with -g. "sudo npm install -g <package-name>" works neither.

**Comment by vohzd** [comment] 2019-10-21 15:26
yep, builds are broken - please add support!

**Comment by sykeben** [comment] 2019-10-22 16:11
I would love to continue developing with Node, too! I recently replaced Windows 10 with Ubuntu 19.10 and when it came time to reinstall nodejs, the installer seemed to fail here:
```sh
## Confirming "eoan" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_12.x/dists/eoan/Release'

## Your distribution, identified as "eoan", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by creid58** [comment] 2019-10-23 04:17
Please add support

**Comment by RAYs3T** [comment] 2019-10-23 07:34
Please add support for eoan.

**Comment by DorkmasterFlek** [comment] 2019-10-23 20:07
Voicing support for this.

**Comment by christopherMills** [comment] 2019-10-24 07:26
nvm is the best way of installing node until this is fixed.

**Comment by CodingVampyre** [comment] 2019-10-24 08:16
Since it seems to take a bit longer, I also want to voice need of installing node 12 || 13!

**Comment by SergioGlorias** [comment] 2019-10-24 08:34
the only wood I found to use node 12.x
without waiting for the repo to be updated

is to enter repo and download .deb normally

but the problem is that there is no automatic update

who wants the intalators deb
**13.x**: https://deb.nodesource.com/node_13.x/pool/main/n/nodejs/
**12.x**: https://deb.nodesource.com/node_12.x/pool/main/n/nodejs/
**10.x**: https://deb.nodesource.com/node_10.x/pool/main/n/nodejs/

**Comment by mortadda** [comment] 2019-10-24 17:50
for now we can do this :



```
$  sudo apt-get install curl
$  curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -

$  nano /etc/apt/sources.list.d/nodesource.list
# add this lines 
deb https://deb.nodesource.com/node_12.x disco main 
deb-src https://deb.nodesource.com/node_12.x disco main

$  sudo apt-get update
$  sudo apt-get install nodejs
```

now 
```
$ nodejs -v
v12.13.
```

**Comment by JungMinu** [comment] 2019-10-25 06:28
Hi, we're in the middle of adding support for Ubuntu 19.10 and will keep you guys updated

**Comment by Congelli501** [comment] 2019-10-28 00:12
Support for Ubuntu 19.10 / eoan is in place for 12.x & 13.x :confetti_ball:!
(I just saw the repo & install script were now working, i don't have any credit for it).

A proper nodesource team announcement will probably follow.

**Comment by JungMinu** [comment] 2019-10-28 06:24
We've added support for Ubuntu 19.10 and thus closing this issue

**Closed** 2019-10-28 06:24 UTC

**Comment by petercunha** [comment] 2019-10-28 17:58
![JackieChan.gif](https://thumbs.gfycat.com/WindyBlandBengaltiger-size_restricted.gif)

**Comment by jwatt** [comment] 2019-11-08 11:08
@JungMinu The version number in the `Description` line in https://deb.nodesource.com/node_13.x/dists/eoan/Release is wrong. It says "for the Node.JS 12.x Branch" instead of "for the Node.JS 13.x Branch.

**Comment by jwatt** [comment] 2019-11-08 11:11
In fact that seems to be the case for all `Release` files under that directory that I checked.

**Comment by khteh** [comment] 2019-11-20 06:15
> We've added support for Ubuntu 19.10 and thus closing this issue

Don't think so:
```
 $ curl -sL --insecure https://deb.nodesource.com/setup_13.x | sudo bash -
## Installing the NodeSource Node.js 13.x repo...


## Populating apt-get cache...

+ apt-get update
Get:1 http://packages.microsoft.com/repos/vscode stable InRelease [3,959 B]
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                
Hit:3 http://dl.google.com/linux/chrome/deb stable Release                                                                                               
Get:4 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages [152 kB]                               
Hit:6 http://ppa.launchpad.net/linuxuprising/java/ubuntu eoan InRelease                                                                          
Hit:7 http://sg.archive.ubuntu.com/ubuntu eoan InRelease                                                          
Hit:8 http://archive.canonical.com/ubuntu eoan InRelease                                    
Hit:10 http://sg.archive.ubuntu.com/ubuntu eoan-updates InRelease     
Hit:11 http://sg.archive.ubuntu.com/ubuntu eoan-backports InRelease          
Hit:9 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease
Hit:12 http://security.ubuntu.com/ubuntu eoan-security InRelease
Fetched 156 kB in 6s (24.8 kB/s)                                                                                                                                                                                  
Reading package lists... Done

## Confirming "eoan" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_13.x/dists/eoan/Release'

## Your distribution, identified as "eoan", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by jwatt** [comment] 2019-11-20 14:34
Note that it looks like eoan support was only added going back as far as node 10:

https://deb.nodesource.com/node_10.x/dists/eoan/Release

If you're trying to use an earlier node release you'd still expect to get that error message.
